-- Attente actions: Profiter Garantie / Maintenance
ALTER TYPE "public"."StatutVoitureSAV" ADD VALUE IF NOT EXISTS 'EN_TRAITEMENT_EN_COURS';
ALTER TYPE "public"."StatutVoitureSAV" ADD VALUE IF NOT EXISTS 'EN_TRAITEMENT_FINI';
ALTER TYPE "public"."StatutVoitureSAV" ADD VALUE IF NOT EXISTS 'EN_MAINTENANCE_EN_COURS';
ALTER TYPE "public"."StatutVoitureSAV" ADD VALUE IF NOT EXISTS 'EN_MAINTENANCE_FINI';
