export const SECTEUR_ACTIVITE_OPTIONS = [
	"Secteur Public",
	"Agro-Industrie",
	"Sécurité",
	"Santé",
	"Education",
	"Recherche",
	"Environnement",
	"Tourisme",
	"Hôtellerie",
	"Restauration",
	"Commerce",
	"Industrie",
	"Agriculture",
	"Artisanat",
	"Services",
	"Finance",
	"Culture",
	"Sport",
	"Technologie",
	"Autres",
	"Artisanat",
	"Industrie",
	"Mines & Énergie",
	"Services & Finance",
	"BTP & Infrastructures",
	"Transport & Logistique",
	"Santé & Social",
	"Professions Libérales",
	"Hôtellerie de Luxe & Affaires",
	"Tourisme & Loisirs",
	"Grande Distribution",
	"Commerce de Détail & E-commerce",
	"Événementiel & Traiteurs",
] as const;
